export const START_COMMENT          = Symbol('~{')
export const END_COMMENT            = Symbol('}~')
export const PREVIOUS_VALUE         = Symbol('PREVIOUS_VALUE')
export const PREVIOUS_EVENT_HANDLER = Symbol('PREVIOUS_EVENT_HANDLER')
export const BOOLEAN_ATTRS          = new Set(['disabled', 'checked', 'selected', 'hidden', 'readonly'])
